CREATE DATABASE BikeStoreProject;

USE BikeStoreProject;

DROP TABLE IF EXISTS stores;
CREATE TABLE stores (
  store_id INT PRIMARY KEY,
  store_name VARCHAR(255) NOT NULL,
  phone VARCHAR(25),
  email VARCHAR(255),
  street VARCHAR(255),
  city VARCHAR(255),
  state VARCHAR(50),
  zip_code VARCHAR(20)
);
LOAD DATA LOCAL INFILE 'C:/Users/penme/Downloads/bike_store/stores.csv'
INTO TABLE stores
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

DROP TABLE IF EXISTS customers;
CREATE TABLE customers (
  customer_id INT PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  phone VARCHAR(25),
  email VARCHAR(255),
  street VARCHAR(255),
  city VARCHAR(255),
  state VARCHAR(50),
  zip_code VARCHAR(20)
);
LOAD DATA LOCAL INFILE 'C:/Users/penme/Downloads/bike_store/customers.csv'
INTO TABLE customers
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

DROP TABLE IF EXISTS brands;
CREATE TABLE brands (
  brand_id INT PRIMARY KEY,
  brand_name VARCHAR(255) NOT NULL
);
LOAD DATA LOCAL INFILE 'C:/Users/penme/Downloads/bike_store/brands.csv'
INTO TABLE brands
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

DROP TABLE IF EXISTS categories;
CREATE TABLE categories (
  category_id INT PRIMARY KEY,
  category_name VARCHAR(255) NOT NULL
);
LOAD DATA LOCAL INFILE 'C:/Users/penme/Downloads/bike_store/categories.csv'
INTO TABLE categories
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

DROP TABLE IF EXISTS orders;
CREATE TABLE orders (
  order_id INT PRIMARY KEY,
  customer_id INT NOT NULL,
  order_status VARCHAR(50),
  order_date DATE,
  required_date DATE,
  shipped_date DATE,
  store_id INT NOT NULL,
  staff_id INT NOT NULL
);
LOAD DATA LOCAL INFILE 'C:/Users/penme/Downloads/bike_store/orders.csv'
INTO TABLE orders
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

DROP TABLE IF EXISTS order_items;
CREATE TABLE order_items (
  order_id INT NOT NULL,
  item_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL,
  list_price DECIMAL(10,2) NOT NULL,
  discount DECIMAL(5,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (order_id, item_id)
);
LOAD DATA LOCAL INFILE 'C:/Users/penme/Downloads/bike_store/order_items.csv'
INTO TABLE order_items
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

DROP TABLE IF EXISTS products;
CREATE TABLE products (
  product_id INT PRIMARY KEY,
  product_name VARCHAR(255) NOT NULL,
  brand_id INT NOT NULL,
  category_id INT NOT NULL,
  model_year SMALLINT NOT NULL,
  list_price DECIMAL(10,2) NOT NULL
);
LOAD DATA LOCAL INFILE 'C:/Users/penme/Downloads/bike_store/products.csv'
INTO TABLE products
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

DROP TABLE IF EXISTS staffs;
CREATE TABLE staffs (
  staff_id INT PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(25),
  active TINYINT NOT NULL,
  store_id INT NOT NULL,
  manager_id INT
);
LOAD DATA LOCAL INFILE 'C:/Users/penme/Downloads/bike_store/staffs.csv'
INTO TABLE staffs
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

DROP TABLE IF EXISTS stocks;
CREATE TABLE stocks (
  store_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL,
  PRIMARY KEY (store_id, product_id)
);
LOAD DATA LOCAL INFILE 'C:/Users/penme/Downloads/bike_store/stocks.csv'
INTO TABLE stocks
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

SHOW TABLES;

USE BikeStoreProject;

-- 1. Store Performance – Total revenue generated by each store
SELECT
  s.store_name,
  ROUND(SUM(oi.list_price * oi.quantity * (1 - oi.discount)), 2) AS total_revenue
FROM stores s
JOIN orders o
  ON s.store_id = o.store_id
JOIN order_items oi
  ON o.order_id = oi.order_id
GROUP BY s.store_name
ORDER BY total_revenue DESC;

-- 2. Product Popularity – Top 5 most sold products by quantity
SELECT
  p.product_name,
  SUM(oi.quantity) AS total_units_sold
FROM products p
JOIN order_items oi
  ON p.product_id = oi.product_id
JOIN orders o
  ON oi.order_id = o.order_id
GROUP BY p.product_name
ORDER BY total_units_sold DESC
LIMIT 5;

-- 3. Customer Location – Customers who placed orders with store names
SELECT
  c.customer_id,
  c.first_name,
  c.last_name,
  c.phone,
  c.email,
  c.city,
  c.state,
  c.zip_code,
  s.store_name
FROM customers c
JOIN orders o
  ON c.customer_id = o.customer_id
JOIN stores s
  ON o.store_id = s.store_id
ORDER BY c.last_name, c.first_name, s.store_name;

-- 4. Brand Insights – Total number of products per brand
SELECT
  b.brand_name,
  COUNT(p.product_id) AS total_products
FROM brands b
JOIN products p
  ON b.brand_id = p.brand_id
GROUP BY b.brand_name
ORDER BY total_products DESC;

-- 5. Low Stock Alert – Products with zero quantity in stock
SELECT
  st.store_id,
  st.store_name,
  p.product_name,
  stck.quantity
FROM stocks stck
JOIN stores st
  ON stck.store_id = st.store_id
JOIN products p
  ON stck.product_id = p.product_id
WHERE stck.quantity = 0
ORDER BY st.store_name, p.product_name;